<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= CONFIG_SITE_TITLE ?></title> <!-- equivalent a ?php echo ... -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #carouselExampleIndicators img {
            aspect-ratio: 16/10;
        }
    </style>
</head>

<body>
    <!-- HEADER -->
    <header>

        <nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="?page=home">
                    <img src=".\assets\images\3244020_feed_media_social_icon.png" alt="logo" width="40" height="40">
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === 'home') echo "active"; ?>" aria-current="page" href="?page=home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === 'gallery') echo "active"; ?>" href="?page=gallery">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === 'contact') echo "active"; ?>" href="?page=contact">Contact</a>
                        </li>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input name="page" value="search" type="hidden">
                        <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <?php if (!isset($_SESSION['user'])): ?>
                    <a class="btn btn-success ms-2" href="?page=login">Login</a>
                    <?php else: ?>
                    <a class="btn btn-danger ms-2" href="?page=logout">Logout</a>
                    <?php endif; ?>
                </div>
            </div>
        </nav>

    </header>

    <main class="container-fluid">
        <!-- MAIN -->
        <?php include "./views/template_" . $page . ".phtml" ?>
    </main>

    <!-- FOOTER -->
    <footer class="bg-dark text-white text-center p-2">
        <p>Ceci est un footer</p>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>