<h1 class="text-center">Search Results for <?= $keywords ?> </h1>


<section class="row row-cols-1 row-cols-md-3 g-4"">
    <?php foreach ($posts as $article) : ?> 
        <article>
        <div class=" card mb-3 ">
        <a href="?page=post_detail&id=<?= $article['id'] ?>"><img src="<?= $article['image'] ?>" class="card-img-top" alt="<?= $article['title'] ?>"></a>
            <div class="card-body bg-light">
                <h5 class="card-title text-white"><?= $article['title'] ?></h5>
                <p class="card-text text-white"><?= substr($article['description'], 0, 100) ?></p>
                <p class="card-text text-white"><small>Rédigé le <?= substr($article['created_at'], 0, 10) ?> par </small> <img src="<?= $article['avatar'] ?>" alt="default profile image" width="32" height="32" class="rounded-circle" /> <strong><?= $article['name'] ?> <?= $article['firstname'] ?></strong></p>
                <a href="?page=post_detail&id=<?= $article['id'] ?>" class="btn btn-secondary">Lire la suite</a>
            </div>
        </div>
    </article>

    <?php endforeach; ?>
</section>