<h1 class="text-center mb-5"><?= $article['title'] ?></h1>
<article class="container">
    <div class=" card mb-3">
        <img src="<?= $article['image'] ?>" class="card-img-top" alt="<?= $article['title'] ?>">
        <div class="card-body">
            <p class="card-text"><?= $article['description'] ?></p>
            <p class="card-text"><small>Rédigé le <?= substr($article['created_at'], 0, 10) ?> par </small> <img src="<?= $article['avatar'] ?>" alt="default profile image" width="32" height="32" class="rounded-circle" /> <strong><?= $article['name'] ?> <?= $article['firstname'] ?></strong></p>
        </div>
    </div>


    <div class="container justify-content-center mt-100 mb-100">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Recent Comments</h4>
                    </div>
                    <?php foreach ($comments as $comment) : ?>
                        <div class="comment-widgets m-b-20">
                            <div class="d-flex flex-row comment-row">
                                <div class="p-2">
                                    <span class="round"><img src="<?= $comment['avatar'] ?>" alt="default profile image" width="50" height="50"></span>
                                </div>
                                <div class="comment-text w-100">
                                    <div class="modal-header p-3">
                                    <h5><?= $comment['name'] ?> <?= $comment['firstname'] ?></h5>
                                    <?php if (isRole('ROLE_ADMIN')) : ?>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="confirmDelete(<?= $comment['id'] ?>)"></button>
                                    <?php endif; ?>
                                    </div>
                                    
                                    <p class="border-bottom pb-3 m-t-10"><?= $comment['comment'] ?></p>
                                    <div class="comment-footer">
                                        <p class="date text-muted mb-3"><small> le <?= substr($comment['created_at'], 0, 10) ?> à <?= substr($comment['created_at'], 11, 5) ?></small></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>
    </div>

    <?php if (isRole('ROLE_ADMIN') || (isRole('ROLE_MEMBER'))) : ?>
        <h3 class="text-center mt-5 mb-2"> Laisser un commentaire </h3>
        <form class="container-fluid  row g-3 " method="POST" action="?page=post_detail&id=<?= $article['id'] ?>">
            <div class="col-md-12">
                <textarea type="text" class="form-control" id="comment" name="comment" placeholder="Entrez un commentaire"></textarea>
            </div>
            <div class="col-12 mb-5">
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </div>
        </form>
    <?php endif; ?>
</article>

<script>
    function confirmDelete(id) {
        const question = window.confirm("Are you sure you want to delete this comment ?");
        if (question) {
            window.location.href = `?page=admin_post_delete&com_id=${id}`
        }
    }
</script>