<h1 class="text-center mb-5"><?= $article['title'] ?></h1>
<article class="container">
    <div class=" card mb-3 ">
        <img src="<?= $article['image'] ?>" class="card-img-top" alt="<?= $article['title'] ?>">
        <div class="card-body">
            <p class="card-text"><?= $article['description'] ?></p>
            <p class="card-text"><small>Rédigé le <?= $article['created_at'] ?> par </small><strong><?= $article['name'] ?> <?= $article['firstname'] ?></strong></p>
        </div>
    </div>
</article>

<h3 class="text-center mb-2"> Laissez un commentaire </h3>
<form class="row g-3" method="POST" action="?page=post_detail&id=<?= $article['id'] ?>">
<div class="col-md-12">
            <label for="description" class="form-label">Description</label>
            <textarea type="text" class="form-control" id="description" name="description"> <?= $post['description'] ?></textarea>
        </div>
</form>