<h1 class="text-center"><?= CONFIG_SITE_TITLE ?></h1>

<?php if (isset($_SESSION['user']['roles']) && in_array('ROLE_ADMIN', json_decode($_SESSION['user']['roles']))): ?>
    <div class="alert alert-info" role="alert">
        <p>Vous etes connecté en tant que <strong>ADMIN</strong></p>
    </div>
<?php endif; ?>
<!-- CAROUSEL DYNAMIQUE -->
<section class="carousel" >
    <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
         <div class="carousel-inner" >
        <!-- DEBUT DE LA BOUCLE FOREACH -->
        <?php foreach ($posts as $key => $article) : ?>

            <div class="carousel-item <?php if ($key===array_key_first($posts)) echo "active" ?>" >
                <img src="<?= $article['image'] ?>" class="d-block w-100" alt="<?= $article['title'] ?>">
                <div class="carousel-caption d-none d-md-block">
                    <h5><?= $article['title'] ?></h5>
                    <p><?= $article['description'] ?></p>
                </div>
            </div>

        <?php endforeach; ?>
        <!-- FIN DE LA BOUCLE FOREACH -->
    </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

<h2 class="text-center">Home</h2>
<p><?= CONFIG_SITE_SLOGAN ?></p>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cumque numquam hic voluptatem consectetur! Quae aliquid quam hic ea possimus laudantium ratione ut neque quasi vero earum, laboriosam voluptate labore excepturi.</p>
