<h1 class="text-center">Admin Dashboard</h1>
<p>Il est temps d'administrer</p>
<a class="btn btn-primary <?php if(isset($_GET['page']) && $_GET['page']==='admin') echo "active"; ?>" aria-current="page" href="?page=admin">Post</a>
<a class="btn btn-primary <?php if(isset($_GET['page']) && $_GET['page']==='admin_user') echo "active"; ?>" aria-current="page" href="?page=admin_user">User</a>
<h2>Handle user</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">First Name</th>
      <th scope="col">adress</th>
      <th scope="col">adress 2</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Zip Code</th>
      <th scope="col">Message</th>
      <th scope="col">Created at</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($contacts as $contact) : ?>
    <tr>
      <th scope="row"><?= $contact['id'] ?></th>
      <td><?= $contact['name'] ?></td>
      <td><?= $contact['firstname'] ?></td>
      <td><?= $contact['adress'] ?></td>
      <td><?= $contact['adress2'] ?></td>
      <td><?= $contact['city'] ?></td>
      <td><?= $contact['state'] ?></td>
      <td><?= $contact['code_postal'] ?></td>
      <td><?= $contact['message'] ?></td>
      <td><?= $contact['created_at'] ?></td>
      <td>
        <a class="btn btn-info">Edit</a>
        <a class="btn btn-danger" href="javascript:confirmDeleteUser(<?= $contact['id'] ?>)">Delete</a>
    </td>
    </tr>
    <?php endforeach; ?>  
  </tbody>
</table>
<a class="btn btn-success mb-3" href="#">Add new user</a>
<script>
  function confirmDeleteUser(id) {
    const question = window.confirm("Are you sure you want to delete this user ?");
    if (question) {
      window.location.href = `?page=admin_user_delete&contact=${id}`
    }
  }
</script>