<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=CONFIG_SITE_TITLE ?></title>
</head>
<body>
    <header>
        <h1>MVC TRAINING</h1>
        <nav>
            <ul>
                <?php foreach(CONFIG_SITE_ROUTES as $route): ?>
                    <li><a href="?page=<?=$route?>"><?=$route?></a></li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </header>
    <?php include("./views/template_".$page.".phtml"); ?>
</body>
</html>