<h1 class="text-center">HOME</h1>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa repellendus autem, est omnis sunt ex dolorem quas numquam vel inventore temporibus blanditiis minima adipisci enim! Eos, expedita? Officiis, deserunt repellat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque aspernatur necessitatibus cum incidunt, temporibus porro nobis numquam molestiae sapiente dolorem, autem vel at in laboriosam cupiditate error repudiandae possimus adipisci!</p>

<?php 
var_dump($fruits);
?>