<h1 class="text-center">Login</h1>
<?php if (isset($data["errors"]) && ($data["errors"])): ?>
        <?php foreach($data["errors"] as $error): ?>
            <div class="alert alert-danger" role="alert">
                <?= $error ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (!isset ($_SESSION['user'])): ?>
<form action="?page=login" method="POST">
  <div class="row mb-3">
    <label for="email" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
    </div>
  </div>
  <div class="row mb-3">
    <label for="password" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" name="password" required>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-10 offset-sm-2">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="remember_me" name="remember_me">
        <label class="form-check-label" for="remember_me">
          Se souvenir de moi
        </label>
      </div>
    </div>
  </div>
  <button type="submit" class="btn btn-dark mb-3">Connexion</button>
  
  <?php else :?>
    <script>
        let timeout= 3;
        setInterval(function() {
            document.getElementById('timeout').innerText = timeout;
            timeout--;
        },1000)
        window.setTimeout(function() {
            window.location.href = "?page=home";
        },4000)
    </script>
    <div class="alert alert-success" role="alert">
            <p>Connexion reussie, Vous allez être rediriger vers la page d'accueil dans <span id="timeout"></span> secondes</p>
    </div>
<?php endif; ?>
</form>